"""initial_schema

Revision ID: 3521fc9902bc
Revises: 
Create Date: 2026-04-19 20:29:05.786468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3521fc9902bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('comuna', sa.String(length=100), nullable=True),
    sa.Column('fono_particular', sa.String(length=30), nullable=True),
    sa.Column('fono_oficina', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('forma_pago_default', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('rut')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_table('intentos_login',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_intento', sa.String(length=50), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_login_username_intento'), 'intentos_login', ['username_intento'], unique=False)
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_modulo'), 'permisos', ['modulo'], unique=False)
    op.create_table('repuestos',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('precio_costo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_repuestos_nombre'), 'repuestos', ['nombre'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnicos_codigo'), 'tecnicos', ['codigo'], unique=True)
    op.create_index(op.f('ix_tecnicos_nombre'), 'tecnicos', ['nombre'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=80), nullable=False),
    sa.Column('modulo', sa.String(length=80), nullable=False),
    sa.Column('entidad_id', sa.String(length=80), nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_entidad_id'), 'auditoria', ['entidad_id'], unique=False)
    op.create_index('ix_auditoria_fecha', 'auditoria', ['fecha'], unique=False)
    op.create_index(op.f('ix_auditoria_modulo'), 'auditoria', ['modulo'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_id'), 'auditoria', ['usuario_id'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones', ['usuario_id'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('vehiculos',
    sa.Column('patente', sa.String(length=12), nullable=False),
    sa.Column('cliente_rut', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('sub_modelo', sa.String(length=80), nullable=True),
    sa.Column('tipo', sa.Enum('AUTO', 'SUV', 'CAMIONETA', 'CAMION', 'FURGON', 'MOTO', 'OTRO', name='tipo_vehiculo_enum'), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('chasis_vin', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_rut'], ['clientes.rut'], ),
    sa.PrimaryKeyConstraint('patente'),
    sa.UniqueConstraint('chasis_vin')
    )
    op.create_index(op.f('ix_vehiculos_cliente_rut'), 'vehiculos', ['cliente_rut'], unique=False)
    op.create_index(op.f('ix_vehiculos_marca'), 'vehiculos', ['marca'], unique=False)
    op.create_index(op.f('ix_vehiculos_modelo'), 'vehiculos', ['modelo'], unique=False)
    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_ot', sa.String(length=30), nullable=False),
    sa.Column('patente', sa.String(length=12), nullable=False),
    sa.Column('cliente_rut', sa.String(length=20), nullable=False),
    sa.Column('recepcionista_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_prometida', sa.Date(), nullable=True),
    sa.Column('fecha_termino', sa.Date(), nullable=True),
    sa.Column('kms_ingreso', sa.Integer(), nullable=True),
    sa.Column('glosa_general', sa.Text(), nullable=True),
    sa.Column('forma_pago', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTA', 'EN_PROCESO', 'LISTA', 'FACTURADA', 'CERRADA', name='estado_ot_enum'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_rut'], ['clientes.rut'], ),
    sa.ForeignKeyConstraint(['patente'], ['vehiculos.patente'], ),
    sa.ForeignKeyConstraint(['recepcionista_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ot')
    )
    op.create_index(op.f('ix_ordenes_trabajo_cliente_rut'), 'ordenes_trabajo', ['cliente_rut'], unique=False)
    op.create_index('ix_ordenes_trabajo_estado', 'ordenes_trabajo', ['estado'], unique=False)
    op.create_index('ix_ordenes_trabajo_numero_ot', 'ordenes_trabajo', ['numero_ot'], unique=False)
    op.create_index(op.f('ix_ordenes_trabajo_patente'), 'ordenes_trabajo', ['patente'], unique=False)
    op.create_table('ot_mano_obra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_trabajo', sa.Text(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('bonificacion', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_neto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_con_impuesto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ot_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_mano_obra_ot_id'), 'ot_mano_obra', ['ot_id'], unique=False)
    op.create_index(op.f('ix_ot_mano_obra_tecnico_id'), 'ot_mano_obra', ['tecnico_id'], unique=False)
    op.create_table('ot_repuestos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_codigo', sa.String(length=40), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_venta_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuento_pct', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('es_siniestro', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tipo', sa.Enum('REPUESTO', 'MATERIAL', 'OTRO', name='tipo_item_ot_enum'), nullable=False),
    sa.ForeignKeyConstraint(['ot_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['repuesto_codigo'], ['repuestos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_repuestos_ot_id'), 'ot_repuestos', ['ot_id'], unique=False)
    op.create_index(op.f('ix_ot_repuestos_repuesto_codigo'), 'ot_repuestos', ['repuesto_codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ot_repuestos_repuesto_codigo'), table_name='ot_repuestos')
    op.drop_index(op.f('ix_ot_repuestos_ot_id'), table_name='ot_repuestos')
    op.drop_table('ot_repuestos')
    op.drop_index(op.f('ix_ot_mano_obra_tecnico_id'), table_name='ot_mano_obra')
    op.drop_index(op.f('ix_ot_mano_obra_ot_id'), table_name='ot_mano_obra')
    op.drop_table('ot_mano_obra')
    op.drop_index(op.f('ix_ordenes_trabajo_patente'), table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_numero_ot', table_name='ordenes_trabajo')
    op.drop_index('ix_ordenes_trabajo_estado', table_name='ordenes_trabajo')
    op.drop_index(op.f('ix_ordenes_trabajo_cliente_rut'), table_name='ordenes_trabajo')
    op.drop_table('ordenes_trabajo')
    op.drop_index(op.f('ix_vehiculos_modelo'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_marca'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_cliente_rut'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_auditoria_usuario_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_modulo'), table_name='auditoria')
    op.drop_index('ix_auditoria_fecha', table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_entidad_id'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tecnicos_nombre'), table_name='tecnicos')
    op.drop_index(op.f('ix_tecnicos_codigo'), table_name='tecnicos')
    op.drop_table('tecnicos')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_repuestos_nombre'), table_name='repuestos')
    op.drop_table('repuestos')
    op.drop_index(op.f('ix_permisos_modulo'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_intentos_login_username_intento'), table_name='intentos_login')
    op.drop_table('intentos_login')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
