"""add_ot_checklist

Revision ID: 588482f25462
Revises: 3521fc9902bc
Create Date: 2026-04-19 20:55:07.488668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588482f25462'
down_revision: Union[str, None] = '3521fc9902bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_checklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ot_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=120), nullable=False),
    sa.Column('completado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ot_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_checklist_ot_id'), 'ot_checklist', ['ot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ot_checklist_ot_id'), table_name='ot_checklist')
    op.drop_table('ot_checklist')
    # ### end Alembic commands ###
